version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  backend:
    build: ./Backend
    ports: 
      - "8000:8000"
    environment:
      URI: mongodb://mongodb:27017
  
  helper:
    build: ./helper
    ports:
      - "3000:3000"
  
  frontend:
    build: ./PortfolioApp
    ports:
      - "5173:5173"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.config:/usr/share/logstash/pipeline/logstash.config
    command: logstash -f /usr/share/logstash/pipeline/logstash.config
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  mongodb_data: {}


