version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  backend:
    build: ./Backend
    ports: 
      - "8080:8080"
    depends_on:
      - mongodb
  
  helper:
    build: ./helper
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  frontend:
    build: ./PortfolioApp
    ports:
      - "5173:5173"
    depends_on:
      - backend  

volumes:
  mongodb_data:

