version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  
  backend:
    build: ./Backend
    ports: 
      - "8000:8000"
    environment:
      URI: mongodb://mongodb:27017
      # LOGSTASH_HOST: logstash

  helper:
    build: ./helper
    ports:
      - "3000:3000"
  
  frontend:
    build: ./PortfolioApp
    ports:
      - "5173:5173"
  
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
  #   restart: always
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.10.1
  #   volumes:
  #   - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.config 
  #   depends_on:
  #     - elasticsearch
        
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.10.1
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200 

volumes:
  mongodb_data: {}