---
- name: Running Docker Compose
  hosts: all
  tasks:

    - name: Running Docker Compose
      command: docker-compose up -d --build

    - name: Pruning Docker images
      command: docker image prune --force